# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
target "TesteHTTP" do
    pod 'Alamofire', '~> 3.4'
end
